# Generated by Django 5.1.1 on 2024-10-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
    ]
