# Generated by Django 5.1.1 on 2024-10-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='precio_costo',
        ),
    ]
