# Generated by Django 5.1.1 on 2024-10-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_remove_ingreso_precio_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='precio_costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
