# Generated by Django 5.2.8 on 2025-11-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_carro_delete_productocompra'),
        ('MainApp', '0008_cart_cartitem'),
    ]

    operations = [
    ]
