# Generated by Django 5.1.3 on 2025-11-21 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_merge_20251120_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
