# Generated by Django 5.1.3 on 2025-11-21 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_productocompra_delete_carro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(max_length=20)),
                ('accounting_date', models.CharField(max_length=10)),
                ('monto_total', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('productos', models.JSONField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
