# Generated by Django 5.1.3 on 2025-12-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
