# Generated by Django 5.1.3 on 2025-12-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
