# Generated by Django 5.1.3 on 2025-12-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_visita'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visita',
            new_name='Visitas',
        ),
    ]
