# Generated by Django 5.1.3 on 2025-12-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_rename_visita_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
