# Generated by Django 5.1.3 on 2025-12-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_alter_visitas_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitas',
        ),
    ]
