# Generated by Django 5.1.3 on 2025-12-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_ordeninvitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=255)),
                ('monto_total', models.IntegerField()),
                ('detalle', models.JSONField()),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='MainApp.ordeninvitado')),
            ],
        ),
    ]
