# Generated by Django 5.1.3 on 2025-12-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_boletainvitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_entrega',
            field=models.CharField(choices=[('retiro', 'Retiro en tienda'), ('envio', 'Envío a domicilio')], default='envio', max_length=20),
        ),
        migrations.DeleteModel(
            name='BoletaInvitado',
        ),
        migrations.DeleteModel(
            name='OrdenInvitado',
        ),
    ]
