# Generated by Django 5.1.3 on 2025-12-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_compra_tipo_entrega_delete_boletainvitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
